on:
  push:
    branch: [ ci ]
    
  workflow_dispath:
  
jobs:
  test:
    run-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        contine-on-error: true
        with:
          install-command: npm install
          browser: chrome
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
